spring:
  application:
    name: Crawler

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: rabbitmq
    password: rabbitmq

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/zhihu
    username: postgres
    password: postgres
    platform: POSTGRESQL
    driver-class-name: org.postgresql.Driver
    maxActive: 50
    initialSize: 10
    maxWait: 60000
    minIdle: 6
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20



mybatis:
  mapperLocations: classpath:mybatis/*.xml